services:
    postgres:
        container_name: postgres-database
        image: postgres:17
        restart: unless-stopped
        ports:
            - '${DB_PORT:-5435}:5432'
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - pg-data:/var/lib/postgresql/data

volumes:
    pg-data:
